site_name: Stratify OS Documentation
site_url: https://docs.stratifylabs.co
repo_url: https://github.com/StratifyLabs/
repo_name: Github
edit_uri: StratifyDocs/blob/master/docs/
google_analytics: ['UA-75152879-3', 'docs.stratifylabs.co']
theme:
    name: readthedocs
    custom_dir: custom_theme/
nav:
  - Introduction: index.md
  - Guides:
    - Stratify OS: Guide-Stratify-OS.md
    - Code Editor: Guide-Qt-Creator.md
    - ARM Cortex M: Guide-ARM-Cortex-M.md
    - CMake Projects: Guide-CMake.md
    - Filesystems: Guide-Filesystems.md
    - Device Drivers: Guide-Device-Drivers.md
    - Threads: Guide-Threads.md
  - Command Line Manual (sl): sl-manual.md
  - API Reference:
    - C++ StratifyAPI: StratifyAPI.md
    - pthread: StratifyOS/pthread.md
    - unistd: StratifyOS/unistd.md
    - aio: StratifyOS/aio.md
    - dirent: StratifyOS/directory.md
    - time: StratifyOS/time.md
    - signals: StratifyOS/signal.md
    - sched: StratifyOS/sched.md
    - semaphore: StratifyOS/semaphore.md
    - mqueue: StratifyOS/mqueue.md
    - Standard C Library: StratifyOS/stdc.md
    - Error Numbers: StratifyOS/errno.md
